Bandwidth and efficency improvements
hyphacoop/cosmos-consensus-monitor pull request #17
Opened 2022-07-22 21:10 UTC by makeworld-the-better-one

- Websocket messages are only sent when the state has changed, yielding massive outgoing bandwidth reductions
- Sending state updates is now done concurrently, so all websocket clients (up to a limit) will get the update at the same time
- Unnecessary websocket incoming messsage handling was removed

2022-07-24 02:15 UTC, dasanchez requested changes
Thanks @makeworld-the-better-one this is exactly the kind of changes I was hoping for!

2022-07-24 02:15 UTC, dasanchez commented on lint.sh
> +    python -m pylint server/*.py --disable=E1101,W1203,C0103
Let's keep C0103 turned on

2022-07-24 02:15 UTC, dasanchez commented on server/consensus_monitor_server.py
> +async def gather_limit(n, *aws, return_exceptions=False):
This is neat, good find!

- I prefer to have descriptive variable and function names.
  Ideally the name itself will tell me what the variable/function is meant to do with minimum context parsing.
  `n` -> `send_coroutines_limit`?
  `aws` -> `awaits`?
- Why wouldn't we put this function inside the `ConsensusMonitor` class?

2022-07-24 02:15 UTC, dasanchez commented on server/consensus_monitor_server.py
> +MAX_CONCURRENT_SEND_COROS = 100
Why wouldn't we put this inside the `ConsensusMonitor` class?

2022-07-24 02:15 UTC, dasanchez commented on server/consensus_monitor_server.py
> +            if await self.update_state():
This is great

2022-07-24 02:15 UTC, dasanchez commented on server/consensus_monitor_server.py
> +        await websocket.wait_closed()
Excellent

2022-07-24 02:15 UTC, dasanchez commented on server/consensus_monitor_server.py
> +
You can remove the `# Consensus monitor class` line 🙃

2022-07-25 13:38 UTC, makeworld-the-better-one commented on server/consensus_monitor_server.py
> +async def gather_limit(n, *aws, return_exceptions=False):
Fixed names in 4fbf818.

> Why wouldn't we put this function inside the `ConsensusMonitor` class?

I see this as a generic helper function that has no relation to any class, so I left it outside. If you prefer it inside the class I can move it there and just make it a static method.

2022-07-25 14:39 UTC, makeworld-the-better-one commented
After looking over the client side of things, I've made one small change in 4776aeb. Otherwise things look good!

2022-07-26 01:37 UTC, dasanchez approved these changes
Thanks @makeworld-the-better-one!

2022-07-26 01:37 UTC, merged